function constants
global FOLDER_BENCHMARK;
global FOLDER_VEHICLE_DENSITY;
global FOLDER_ZOR_ZOF_LENGTH;
global FOLDER_WIDTH_BETWEEN_BUILDING;

FOLDER_RESULT = fullfile('results');
FOLDER_BENCHMARK = fullfile(FOLDER_RESULT, 'benchmark');
FOLDER_VEHICLE_DENSITY = fullfile(FOLDER_RESULT, 'vehicle_density');
FOLDER_ZOR_ZOF_LENGTH =fullfile(FOLDER_RESULT, 'zor_zof_length');
FOLDER_WIDTH_BETWEEN_BUILDING = fullfile(FOLDER_RESULT, 'width_between_buildings');

global USECASE_BENCHMARK;

global USECASE_VEHICLE_DENSITY_50;
global USECASE_VEHICLE_DENSITY_150;

global USECASE_ZOR_ZOF_LENGTH_500;
global USECASE_ZOR_ZOF_LENGTH_1500;

global USECASE_WIDTH_BETWEEN_BUILDING_20;
global USECASE_WIDTH_BETWEEN_BUILDING_60;

USECASE_BENCHMARK = 0;
USECASE_VEHICLE_DENSITY_50 = 1;
USECASE_VEHICLE_DENSITY_150 = 2;

USECASE_ZOR_ZOF_LENGTH_500 =3;
USECASE_ZOR_ZOF_LENGTH_1500 = 4;

USECASE_WIDTH_BETWEEN_BUILDING_20 = 5;
USECASE_WIDTH_BETWEEN_BUILDING_60 = 6;
end

