function constants
global FOLDER_BENCHMARK;
global FOLDER_VEHICLE_DENSITY;
global FOLDER_ZOR_ZOF_LENGTH;
global FOLDER_WIDTH_BETWEEN_BUILDING;

FOLDER_RESULT = fullfile('results');
FOLDER_BENCHMARK = fullfile(FOLDER_RESULT, 'benchmark');
FOLDER_VEHICLE_DENSITY = fullfile(FOLDER_RESULT, 'vehicle_density');
FOLDER_ZOR_ZOF_LENGTH =fullfile(FOLDER_RESULT, 'zor_zof_length');
FOLDER_WIDTH_BETWEEN_BUILDING = fullfile(FOLDER_RESULT, 'width_between_buildings');

global USECASE_BENCHMARK;%vd 100 zor 500 wbb 40

global USECASE_VEHICLE_DENSITY_50;
global USECASE_VEHICLE_DENSITY_75;
global USECASE_VEHICLE_DENSITY_125;
global USECASE_VEHICLE_DENSITY_150;

global USECASE_ZOR_ZOF_LENGTH_750;
global USECASE_ZOR_ZOF_LENGTH_1000;
global USECASE_ZOR_ZOF_LENGTH_1250;
global USECASE_ZOR_ZOF_LENGTH_1500;

global USECASE_WIDTH_BETWEEN_BUILDING_20;
global USECASE_WIDTH_BETWEEN_BUILDING_30;
global USECASE_WIDTH_BETWEEN_BUILDING_50;
global USECASE_WIDTH_BETWEEN_BUILDING_60;

USECASE_BENCHMARK = 0;

USECASE_VEHICLE_DENSITY_50 = 1;
USECASE_VEHICLE_DENSITY_75 = 2;
USECASE_VEHICLE_DENSITY_125 = 3;
USECASE_VEHICLE_DENSITY_150 = 4;

USECASE_ZOR_ZOF_LENGTH_750 = 5;
USECASE_ZOR_ZOF_LENGTH_1000 =6;
USECASE_ZOR_ZOF_LENGTH_1250 = 7;
USECASE_ZOR_ZOF_LENGTH_1500 = 8;

USECASE_WIDTH_BETWEEN_BUILDING_20 = 9;
USECASE_WIDTH_BETWEEN_BUILDING_30 = 10;
USECASE_WIDTH_BETWEEN_BUILDING_50 = 11;
USECASE_WIDTH_BETWEEN_BUILDING_60 = 12;
end

